     2
     4
     34
     1
     2
     1
  3.0d0
  0.4d0 0.4d0
  0.003d0 
  0.0d0 0.0d0
  1.d3
  2.d-2

 $para1  eup=-1.0d0 edown=-1.0d0 uu=2.0d0  fixdot=T $end

! $field  fieldtype= 1, lreadomega=T  $end
! 0.03 0.03 0.03 0.03

 $field  fieldtype=0  $end
 1.d-20 1.d-20 1.d-20 1.d-20

! $specfunc chkcorr=T  $end

! $combineleads lequileads=T   $end

 $jobinfo  lsparse=T psfjob=T  itype_psf=22  $end

 $converge maxit0=20000 crit=1.d-8   $end

 $adiabatic lad=T  $end
